# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:18
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentSpecial',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
