# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:14
from __future__ import unicode_literals

from django.db import migrations
import draceditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0003_auto_20170612_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=draceditor.models.DraceditorField(default=''),
        ),
    ]
